### ISSUE TITLE
Too Much Information in scoreboard

### ISSUE THREAD

**Issue by whamgames** [Luoti/f1-telemetry#8]
- Remove full name, display 3 character abbreviation
- Add player name abbreviation for WHAM = WHM / Luoti = ???
- Change display format to display fields: Position, Name abbreviation, Time difference to car ahead, Current tyre
- Display purple highlight for fastest time?

**Comment by Luoti** [comment]
- [x] Remove full name, display 3 character abbreviation **DONE Added the abbrevations to settings.** https://github.com/Luoti/f1-telemetry/commit/098890df2493f45a5b5e42b600c3f4398a6cc5fb
- [x] Add player name abbreviation for WHAM = WHM / Luoti = ??? **DONE Added the abbrevations to settings.** https://github.com/Luoti/f1-telemetry/commit/098890df2493f45a5b5e42b600c3f4398a6cc5fb
- [x] Change display format to display fields: Position, Name abbreviation, Time difference to car ahead, Current tyre **DONE Can be configured in settings.**

- [ ] Display purple highlight for fastest time?
This is not so easy. The game does not send fastest time with the driver. We would have to calculate that ourselves and keep the state in sync. Can be done, but maybe we push this to the backlog.

**Comment by Luoti** [comment]
All of this should be done.
